image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - deploy


# Build Job
build-job:
  stage: build
  script:
    - curl "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip" -L -o "aws-sam-cli.zip"
    - unzip aws-sam-cli.zip -d sam-installation
    - echo "Restoring .NET dependencies..."
    - dotnet restore Serverless.UploadsNotificationFunction/src/Serverless.UploadsNotificationFunction  # Restore dependencies
    - echo "Building .NET project..."
    - dotnet build Serverless.UploadsNotificationFunction/src/Serverless.UploadsNotificationFunction -c Release  # Build the project
    - echo "Publishing .NET Lambda..."
    - dotnet publish Serverless.UploadsNotificationFunction/src/Serverless.UploadsNotificationFunction -c Release -f net8.0 -o publish/
    - echo "Building SAM application..."
    - sam build --template template.yaml --use-container  # Build the SAM application using container for Lambda

# Test Job
unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - dotnet test Serverless.UploadsNotificationFunction/src/Tests/  # Replace with your test project path
    - echo "Unit tests completed successfully."

# Deploy Job
deploy-job:
  stage: deploy
  image: amazon/aws-cli:2.12.6  # Use AWS CLI image for deployment
  environment: production
  script:
    - echo "Packaging SAM application..."
    - sam package --s3-bucket omo-bucket-01 --output-template-file packaged.yaml
    - echo "Deploying SAM application to AWS..."
    - sam deploy --template-file packaged.yaml --stack-name ServerlessLambdaStack --capabilities CAPABILITY_IAM
  only:
    - main  # Deploy only from the main branch
